jobs:
  install_authenticate_create_deploy:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      - sfdx/auth:
          defaultusername: rn@su-blitz.org
      - run:
          command: >
            sfdx force:org:create -f ./config/project-scratch-def.json -a test1
          name: Create a new org
      - run:
         command: >
           sfdx force:source:deploy -p ./force-app/main/default/aura -u test1
         name: Deploy to an org   
orbs:
  sfdx: circleci/salesforce-sfdx@2.0.0
version: 2.1
workflows:
  basic-test:
    jobs:
      -  install_authenticate_create_deploy