jobs:
  install_authenticate:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      - sfdx/auth:
          defaultusername: rn@su-blitz.org
      - run:
          command: >
            echo You now have access to the sfdx cli and may execute commands
            against it.
            sfdx force:auth:list
          name: Run your SFDX commands here
orbs:
  sfdx: circleci/salesforce-sfdx@2.0.0
version: 2.1
workflows:
  basic-test:
    jobs:
      - install_authenticate